# Generated by Django 5.1 on 2024-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phoneNo', models.CharField(max_length=20)),
                ('addressDetails', models.JSONField()),
                ('workExperience', models.JSONField()),
                ('qualifications', models.JSONField()),
                ('projects', models.JSONField()),
                ('photo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
