# Generated by Django 5.1 on 2024-08-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='addressDetails',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
